// src/components/ClockPanel.vue
<script setup lang="ts">
import { useTime } from '../composables/useTime';
import type { TimeConfig } from '../types/site';

const props = defineProps<{
    config: TimeConfig;
}>();

const { timeString, dateParts } = useTime(props.config);
</script>

<template>
    <div class="clock">{{ timeString }}</div>
    <div v-if="config.showWeekday" class="weekday">{{ dateParts.weekday }}</div>
    <div v-if="config.showDate && dateParts.dateDisplay" class="date-display">{{ dateParts.dateDisplay }}</div>
</template>

// src/components/ClockPanel.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { formatDateParts, formatTimeString } from '../lib/time';
    import type { TimeConfig } from '../types/site';
    import { getLocale } from '../lib/i18n.svelte';

    let { config }: { config: TimeConfig } = $props();

    let now = $state(new Date());
    let timer: ReturnType<typeof setInterval> | null = null;

    let locale = $derived(getLocale());

    onMount(() => {
        timer = setInterval(() => {
            now = new Date();
        }, config.updateInterval);

        return () => {
            if (timer) clearInterval(timer);
        };
    });

    let dateParts = $derived(formatDateParts(now, locale));
</script>

<div class="clock">{formatTimeString(now, config.format)}</div>
{#if config.showWeekday}
    <div class="weekday">{dateParts.weekday}</div>
{/if}
{#if config.showDate && dateParts.dateDisplay}
    <div class="date-display">{dateParts.dateDisplay}</div>
{/if}
